name: MkDocs Deploy

on:
  push:
<<<<<<< HEAD
    branches: #  Act on master branch commit
    - main
=======
    branches: #  Act on main branch commit
      - main

>>>>>>> development
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: "pip"

      - run: pip install mkdocs-material

      - run: mkdocs gh-deploy --force