name: Documentation Generation
on:
  push:
    branches:
      - main

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - name: Clone project
        uses: actions/checkout@v2

      - name: Clone wiki
        uses: actions/checkout@v2

      - name: Parse and generate documentation
        uses: p3lim/lua-doc-parser@v2
        with:
          output: docs/api

      - name: Push documentation changes
        run: |
          git config user.name "CI"
          git config user.email "<>"
          git add .
          git diff --quiet HEAD || git commit -m "$GITHUB_SHA"
          git push
