name: Publish package to Wally

on:
  push:
    branches: #  Act on main branch commit
      - main
  
jobs:
  publish:
    name: Publish package to Wally
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
  
    - name: Setup Aftman
      uses: ok-nick/setup-aftman@v0.4.2

    - name: Log In
      env:
        WALLY_AUTH: ${{ secrets.WALLY_AUTH }}
      run: |
        mkdir ~/.wally
        printenv WALLY_AUTH > ~/.wally/auth.toml
  
    - name: Publish
      run: |
        wally publish