name: Publish To Roblox

on:
  push:
    branches: #  Act on main branch commit
      - main

jobs:
  ci:
    name: CI and Deployment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ok-nick/setup-aftman@v0.4.2

      - name: Publish to Wally
        run: wally publish --token "${{ secrets.WALLY_AUTH }}"